[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tchecksum"
version = "1.0.2"
description = "CheckSum Calculation Module"
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=2.0"
